### ISSUE TITLE
can provide tif type volume image

### ISSUE THREAD

**Issue by junqiangchen** [trivoldus28/xray-challenge-eval#1]
hi,i want use voluem image for traning Unet3d segmentation,can you share tif type volume image.

**Comment by junqiangchen** [comment]
there is example convert h5 file to volume data

`import SimpleITK as sitk
import h5py


def readhdf5array(filename):
    # open tiff file in read mode
    with h5py.File(filename, "r") as f:
        # Print all root level object names (aka keys)
        # these can be group or dataset names
        print("Keys: %s" % f.keys())
        # get first object name/key; may or may NOT be a group
        a_group_key = list(f.keys())[0]
        # If a_group_key is a dataset name,
        # this gets the dataset values and returns as a list
        data = list(f[a_group_key])
        # preferred methods to get dataset values:
        ds_arr = f[a_group_key][data[0]][()]  # returns as a numpy array
        return ds_arr


def converth52volumeimage():
    filename = r'F:\MedicalData\2023XPRESS\dataset\xpress-training-voxel-labels.h5'
    dataarray = readhdf5array(filename)
    sitk_image = sitk.GetImageFromArray(dataarray)
    sitk.WriteImage(sitk_image, r'F:\MedicalData\2023XPRESS\train_mask.nii.gz')`

**Comment by trivoldus28** [comment]
@junqiangchen Thanks for the example. Sorry I haven't been monitoring the repo but will watch it more closely now.
