### ISSUE TITLE
dtype mismatch in loss calculation

### ISSUE THREAD

**Issue by abhirooptalasila** [trivoldus28/xray-challenge-eval#4]
Hi
I'm trying to replicate the baseline results. I've setup everything up until the training bash script. While running, I get the following error:
> jax._src.traceback_util.UnfilteredStackTrace: TypeError: lax.select requires arguments to have the same dtypes, got float32, float16. (Tip: jnp.where is a similar function that does automatic type promotion on inputs).

Which points to an error on this line
> File "/home/abhiroop.talasila/XPRESS/code/segmentation/networks/reference_setup/mknet.py", line 134, in _train_step
    new_loss_scale = params.loss_scale.adjust(grads_finite)

Any suggestions on how to solve this? Here's the [stack_trace](https://github.com/trivoldus28/xray-challenge-eval/files/10828864/stack_trace.txt)

**Comment by trivoldus28** [comment]
1. Are you running on CPU or GPU?
2. Try setting this variable to False for non-mixed precision training (you'll get the same results, just slower). https://github.com/trivoldus28/xray-challenge-eval/blob/master/segmentation/networks/reference_setup/mknet.py#L35

**Comment by abhirooptalasila** [comment]
I'm trying to run on an RTX 3080TI with CUDA 11.6 (cuDNN 3.4) version of Jaxlib 0.4.4 installed. 
I tried what you suggested, and here's the updated [stack_trace](https://github.com/trivoldus28/xray-challenge-eval/files/10830027/stack_trace.txt).

**Comment by trivoldus28** [comment]
`Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR` -> seems like you have some library/initialization problems. Make sure you can run simple examples like https://github.com/google/jax/blob/main/examples/mnist_classifier.py to make sure that your software stack is working correctly.

Note that for this specific example I found that there's a small typo. Instead of:
`from examples import datasets`
You need to just:
` import datasets`
For the example to run.

**Comment by abhirooptalasila** [comment]
I've tried countless combinations of CUDA/cuDNN/jax/jaxlib which led to one which worked. 
The MNIST example works, but when I try to run this script, I get this error:
> AttributeError: module 'jax' has no attribute 'Array'

Current versions:
funlib.learn.jax         0.1
jax                      0.3.5
jaxlib                   0.3.5+cuda11.cudnn82

Could you please provide your version numbers **ALL** libraries? Otherwise, since Jax doesn't come bundled with CUDA and cuDNN, its virtually impossible to narrow down on one, in my opinion.

**Comment by trivoldus28** [comment]
I have been testing with jax=0.3.25, maybe try upgrading jax? How did you get 0.3.5? Did you install it previously? I would also try with python=>3.10 in a fresh venv.

But yes I'll try update the requirements.txt with the exact versions of the libraries.

**Comment by abhirooptalasila** [comment]
I assumed you must've used older versions of Jax so I was just trying different versions. Now that you mentioned you'd used 0.3.25, I've found a combination that works for me. 

Python 3.10.9 
numpy                    1.23.1
jax                      0.3.25
jaxlib                   0.3.25+cuda11.cudnn82
CUDA 11.6 with cuDNN 8.4 running on RTX 3080TI

The command I used to install Jax
`pip install --upgrade jax==0.3.25 jaxlib==0.3.25+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

But yes, providing accurate package version info would've made things a lot easier. I hope it is updated. 
Thanks for your help!

**Comment by abhirooptalasila** [comment]
Training on 1 GPU shows me the completion time is around 15 hours. But when I use 4 GPUs, the time shoots up to 35 hours. Any idea why this might be happening?

**Comment by trivoldus28** [comment]
@abhirooptalasila I'm glad you got it working! I didn't realize there could be compatibility issues but maybe it's because of the new 0.4.x releases.

**Comment by trivoldus28** [comment]
> Training on 1 GPU shows me the completion time is around 15 hours. But when I use 4 GPUs, the time shoots up to 35 hours. Any idea why this might be happening?

It's because you're training the same # of iterations is the same but the [batch size is linear with # of gpus](https://github.com/trivoldus28/xray-challenge-eval/blob/master/segmentation/networks/reference_setup/train.py#L249), so you are computing 4x the amount of samples. With n gpu training, you should decrease the # of iterations by n, and increase the learning rate by n (https://github.com/trivoldus28/xray-challenge-eval/blob/master/segmentation/networks/reference_setup/mknet.py#L36).

The reason why training time shoots to 35hr instead of remaining at 15hrs is because the front-end that is constructing the batches is doing 4x as much work so you would need more workers. There is also a process-process decoding bottleneck but I'd still expect at most 20-25 hours with more workers.

**Comment by abhirooptalasila** [comment]
That makes sense. Okay so I'll pass `iteration // 4` into `train_until` and change up the LR to `0.5e-4 * 0.5 * 4` right?

**Comment by trivoldus28** [comment]
That's correct, make sure you also increase the # of workers by 4x up to the # of logical cores in the computer for max performance.

**Comment by abhirooptalasila** [comment]
Hi
Training finished in 10 hours. I'm now trying to generate segmentation outputs. I ran the first command and got affs in the output folder. The second command I ran:
> python segway/tasks/segmentation/task_06a_extract_segments.py configs/segment_validation_reference.json

I get a type error. 
```
ERROR:daisy.server:Block ExtractFragmentTask/42 with read ROI [11484:17820, 15708:22044, 15708:22044] (6336, 6336, 6336) and write ROI [12540:16764, 16764:20988, 16764:20988] (4224, 4224, 4224) failed in worker 30 with TypeError("bad operand type for unary -: 'list'")
```

Here's a section from the daisy logs for one of the workers, which is repeated for all individual ROIs.
```
ERROR:daisy.client:Block ExtractFragmentTask/1 with read ROI [7260:13596, 7260:13596, 11484:17820] (6336, 6336, 6336) and write ROI [8316:12540, 8316:12540, 12540:16764] (4224, 4224, 4224) failed in worker 0
Traceback (most recent call last):
  File "/home/abhiroop.talasila/miniconda3/envs/exp/lib/python3.10/site-packages/daisy/client.py", line 85, in acquire_block
    yield block
  File "/home/abhiroop.talasila/XPRESS/code/segmentation/segway/tasks/segmentation/worker_fragment_extract.py", line 112, in <module>
    watershed_in_block(affs,
  File "/home/abhiroop.talasila/miniconda3/envs/exp/lib/python3.10/site-packages/lsd/parallel_fragments.py", line 304, in watershed_in_block
    rag.write_nodes(block.write_roi)
  File "/home/abhiroop.talasila/miniconda3/envs/exp/lib/python3.10/site-packages/daisy/persistence/file_graph_provider.py", line 693, in write_nodes
    assert roi.shift(-self.nodes_roi_offset).begin.is_multiple_of(
TypeError: bad operand type for unary -: 'list'
```

Any idea what could be going wrong?

**Comment by trivoldus28** [comment]
Can you try this fix real quick? `pip install -U git+https://github.com/trivoldus28/daisy@36a698c#egg=daisy`

**Comment by abhirooptalasila** [comment]
Still has the same output. Can you provide the output of `pip3 freeze > requirements.txt`?

**Comment by trivoldus28** [comment]
Here is my working config: https://gist.github.com/trivoldus28/7ac36420a604702e3f5c12efca62febb

**Comment by trivoldus28** [comment]
I've also updated the installation requirements.txt: https://github.com/trivoldus28/xray-challenge-eval/commit/162133ccfcac631c070a060f420e08fc8b08bc2d#diff-43e395064d5784a144b33264e014ab3cd29018a19ed899a35d54c3eeb73b5765

**Comment by abhirooptalasila** [comment]
Thanks for this!
It absolutely worked. I needed to change a few packages, but it did work. 
By the way, `pip freeze` is the default way people publish their projects publicly. Not sure how the initial file was generated.
