### ISSUE TITLE
validation skeleton range?

### ISSUE THREAD

**Issue by junqiangchen** [trivoldus28/xray-challenge-eval#5]
hi,i find validation skeleton is part of the validation image,what is the range in the image?
![image](https://user-images.githubusercontent.com/28638716/222079303-dbaf0048-0619-488c-b93a-f03d760610fa.png)

**Comment by trivoldus28** [comment]
> Note that for the validation volume, we segment only the inner 23um^3 while for the test volume we segment 33um^3 because these are the ROIs of the ground-truth skeletons.
(https://github.com/trivoldus28/xray-challenge-eval/tree/master/segmentation#run-segmentation)

Skeletons are inner 33um^3 for training and testing, and 23um^3 for validation. I'll make it clearer in the data page.

**Comment by trivoldus28** [comment]
I have clarified it in https://github.com/trivoldus28/xray-challenge-eval/tree/master/data#download-ground-truth-skeletons:

> **Note:** the GT skeletons are only fully annotated for the inner 33um volume for `training` and `test`, but is the 23.1um for `validation`. That is:
> - ROI of raw for all three volumes are 39.6 x 39.6 x 39.6 um (1200 x 1200 x 1200 pix at 33nm resolution).
> - ROI of GT skeletons for `training`/`test` is the inner 33 x 33 x 33 um (1000 x 1000 x 1000 pix with an offset of 100 x 100 x 100 pix).
> - ROI of GT skeletons for `validation` is the inner 23.1 x 23.1 x 23.1 um (700 x 700 x 700 pix with an offset of 250 x 250 x 250 pix).

**Comment by junqiangchen** [comment]
@trivoldus28 thank you,i get it!
