### ISSUE TITLE
No module named 'gunpowder.jax'

### ISSUE THREAD

**Issue by havefun0** [trivoldus28/xray-challenge-eval#6]
Hi,

Thanks for your work first. While I have encountered a problem when following your segmentation baseline. It shows that 'ModuleNotFoundError: No module named 'gunpowder.jax'', however, I am sure that I have correctly installed the gunpowder model.

I am using ubuntu 20.04 server, python 3.8

Could you please help to solve the issue?

Thanks so much!

**Comment by trivoldus28** [comment]
@havefun0 You got it working?
